### ISSUE TITLE
CDbException error when installing v.0.0.4

### ISSUE THREAD

**Issue by ax2000** [bossanova808/CommerceRegisterOnCheckout#4]
Hi Jeremy,

When updating to 0.0.4 I'm getting this error on installation. Tried upgrading and reinstalling but no luck.

![screen shot 2017-02-21 at 1 51 16 pm](https://cloud.githubusercontent.com/assets/2585959/23149092/b2a222ec-f83d-11e6-8ef4-7cf69f86a3bc.png)

**Comment by bossanova808** [comment]
Well that's just weird.  Looks like the syntax for table creation and adding columns is different.

(Any reason you didn't just do an upgrade?  It would have modified your original table).

In the main plugin file, can you change thuis function to this

```
    public function onBeforeInstall()
    {
        craft()->db->createCommand()->createTable("commerceregisteroncheckout",["orderNumber"=>"varchar","EPW"=>"varchar", "lastUsedShippingAddressId"=>"integer", "lastUsedBillingAddressId", "integer"]);        
    }
```
...and let me know?

Sorry!  I assumed that the createTable column syntax would match the addColumnAfter syntax,

**Comment by ax2000** [comment]
Thanks for the prompt reply Jeremy.

For whatever reason I uninstalled the plugin while performing tests.

I updated the `onBeforeInstall` function as you said but still getting this:

```CDbCommand failed to execute the SQL statement: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'NULL,
INT(11) NULL,
`dateCreated` datetime NOT NULL,
`dateUpdated` datetime N' at line 6. The SQL statement executed was: CREATE TABLE `craft_commerceregisteroncheckout` (
`id` int(11) NOT NULL AUTO_INCREMENT,
`orderNumber` VARCHAR(255) NULL,
`EPW` VARCHAR(255) NULL,
`lastUsedShippingAddressId` INT(11) NULL,
lastUsedBillingAddressId NULL,
INT(11) NULL,
`dateCreated` datetime NOT NULL,
`dateUpdated` datetime NOT NULL,
`uid` CHAR(36) NOT NULL DEFAULT 0,
PRIMARY KEY (id)
) ENGINE=InnoDb DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci```

Not sure what's going on there

**Comment by bossanova808** [comment]
```
    public function onBeforeInstall()
    {
        craft()->db->createCommand()->createTable("commerceregisteroncheckout",["orderNumber"=>"varchar","EPW"=>"varchar", "lastUsedShippingAddressId"=>"integer", "lastUsedBillingAddressId" => "integer"]);        
    }
```
Sorry, stupid syntax error there - this will work.

**Comment by ax2000** [comment]
Thanks Jeremy,

That fixed the error indeed.

Unfortunately I'm getting something else now.
When doing the ajax call to `/actions/commerceRegisterOnCheckout/saveRegistrationDetails`, I get a 500 with:
```Trying to get property of non-object (/var/www/mmf-craft/craft/plugins/commerceregisteroncheckout/controllers/CommerceRegisterOnCheckoutController.php:21)

#0 /var/www/mmf-craft/craft/app/etc/errors/ErrorHandler.php(184): Craft\ErrorHandler->handleError()
#1 /var/www/mmf-craft/craft/app/framework/base/CErrorHandler.php(133): Craft\ErrorHandler->handleError()
#2 /var/www/mmf-craft/craft/app/framework/base/CApplication.php(834): Craft\ErrorHandler->handle()
#3 /var/www/mmf-craft/craft/app/etc/web/WebApp.php(687): Craft\WebApp->handleError()
#4 /var/www/mmf-craft/craft/plugins/commerceregisteroncheckout/controllers/CommerceRegisterOnCheckoutController.php(21): Craft\WebApp->handleError()
#5 /var/www/mmf-craft/craft/app/framework/web/actions/CInlineAction.php(49): Craft\CommerceRegisterOnCheckoutController->actionSaveRegistrationDetails()
#6 /var/www/mmf-craft/craft/app/framework/web/CController.php(308): CInlineAction->runWithParams()
#7 /var/www/mmf-craft/craft/app/framework/web/CController.php(286): Craft\CommerceRegisterOnCheckoutController->runAction()
#8 /var/www/mmf-craft/craft/app/framework/web/CController.php(265): Craft\CommerceRegisterOnCheckoutController->runActionWithFilters()
#9 /var/www/mmf-craft/craft/app/framework/web/CWebApplication.php(282): Craft\CommerceRegisterOnCheckoutController->run()
#10 /var/www/mmf-craft/craft/app/etc/web/WebApp.php(817): Craft\WebApp->runController()
#11 /var/www/mmf-craft/craft/app/etc/web/WebApp.php(287): Craft\WebApp->_processActionRequest()
#12 /var/www/mmf-craft/craft/app/framework/base/CApplication.php(185): Craft\WebApp->processRequest()
#13 /var/www/mmf-craft/craft/app/index.php(62): Craft\WebApp->run()
#14 /var/www/mmf-craft/public/index.php(19): require_once()```

**Comment by ax2000** [comment]
Nevermind Jeremy.

I'm pretty sure this is something on my end. Please let me check a couple of more things and I'll get back to you

**Comment by bossanova808** [comment]
Sure - yes that looks like something else.  I'll jstu wait for you to confirm then push the fix.  Still find it wierd that two basically the same things use different syntax, but there you go...

**Comment by bossanova808** [comment]
I pushed this out as I don't want anyone else to get stuck with an upgrade...
